// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNcVk99vs1Mh9gNopYNI52o_3u8dDAy_c',
    appId: '1:522694987648:web:908890b7a2ddde1c92fb65',
    messagingSenderId: '522694987648',
    projectId: 'handymar-31b60',
    authDomain: 'handymar-31b60.firebaseapp.com',
    storageBucket: 'handymar-31b60.firebasestorage.app',
    measurementId: 'G-GY968Q8GT3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABJwwYl7YWJfYkAuu__4xIln863cgysnc',
    appId: '1:522694987648:android:d93d8a746d70d02a92fb65',
    messagingSenderId: '522694987648',
    projectId: 'handymar-31b60',
    storageBucket: 'handymar-31b60.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHY4RJSD4RtDmDrha7ENr51mqbNwGmYKQ',
    appId: '1:522694987648:ios:f1ecee43b789bb7492fb65',
    messagingSenderId: '522694987648',
    projectId: 'handymar-31b60',
    storageBucket: 'handymar-31b60.firebasestorage.app',
    iosBundleId: 'com.example.handymarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHY4RJSD4RtDmDrha7ENr51mqbNwGmYKQ',
    appId: '1:522694987648:ios:f1ecee43b789bb7492fb65',
    messagingSenderId: '522694987648',
    projectId: 'handymar-31b60',
    storageBucket: 'handymar-31b60.firebasestorage.app',
    iosBundleId: 'com.example.handymarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNcVk99vs1Mh9gNopYNI52o_3u8dDAy_c',
    appId: '1:522694987648:web:68be9e300dee587892fb65',
    messagingSenderId: '522694987648',
    projectId: 'handymar-31b60',
    authDomain: 'handymar-31b60.firebaseapp.com',
    storageBucket: 'handymar-31b60.firebasestorage.app',
    measurementId: 'G-9N8XKQ3WH1',
  );
}
